# Generated by Django 5.0.1 on 2024-01-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='None Listed', max_length=300),
        ),
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.CharField(default='None Listed', max_length=200),
        ),
    ]
