# Generated by Django 5.0.1 on 2024-01-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_student_address_student_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.CharField(max_length=100),
        ),
    ]
