# Generated by Django 5.0.1 on 2024-01-18 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_classroom_teacher'),
        ('main_app', '0010_teacher_user_alter_student_user'),
    ]

    operations = [
    ]
