# Generated by Django 5.0.1 on 2024-01-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_assignment_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='announcements',
            field=models.CharField(default='No Announcements Yet', max_length=500),
        ),
    ]
