# Generated by Django 5.0.1 on 2024-01-19 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_assignment_teacher'),
        ('main_app', '0016_remove_classroom_student_remove_classroom_teacher_and_more'),
    ]

    operations = [
    ]
