# Generated by Django 5.0.1 on 2024-01-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_merge_20240119_1536'),
        ('main_app', '0017_merge_20240119_1538'),
    ]

    operations = [
    ]
