# Generated by Django 5.0.1 on 2024-01-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_merge_20240119_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at']},
        ),
    ]
