# Generated by Django 5.0.1 on 2024-01-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_assignment_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='google_drive_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
