# Generated by Django 5.0.1 on 2024-01-19 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_announcement_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(default=None, max_length=300)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.announcement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
