# Generated by Django 5.0.1 on 2024-01-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_announcement_options'),
        ('main_app', '0020_assignment_due_date'),
    ]

    operations = [
    ]
