# Generated by Django 5.0.1 on 2024-01-20 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_comment'),
        ('main_app', '0021_merge_20240119_2002'),
    ]

    operations = [
    ]
