# Generated by Django 5.0.1 on 2024-01-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_merge_0020_comment_0021_merge_20240119_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='zoom_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
