# Generated by Django 5.0.1 on 2024-01-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_classroom_zoom_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='students',
            field=models.ManyToManyField(to='main_app.student'),
        ),
    ]
