# Generated by Django 4.2.9 on 2024-01-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_classroom_zoom_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='students',
        ),
        migrations.AddField(
            model_name='classroom',
            name='srudents',
            field=models.ManyToManyField(related_name='student_relation', to='main_app.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ManyToManyField(related_name='classroom_relation', to='main_app.classroom'),
        ),
    ]
