# Generated by Django 4.2.9 on 2024-01-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_remove_classroom_students_classroom_srudents_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='srudents',
            new_name='students',
        ),
    ]
