# Generated by Django 4.2.9 on 2024-01-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_rename_srudents_classroom_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classrooms',
            field=models.ManyToManyField(related_name='classrooms_relation', to='main_app.classroom'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teachers',
            field=models.ManyToManyField(related_name='teacher_relation', to='main_app.teacher'),
        ),
    ]
