# Generated by Django 5.0.1 on 2024-01-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_alter_student_email'),
        ('main_app', '0026_teacher_classrooms_alter_classroom_teachers'),
    ]

    operations = [
    ]
