# Generated by Django 5.0.1 on 2024-01-22 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_assignment_submitted_by_student_and_more'),
        ('main_app', '0027_merge_20240122_1601'),
    ]

    operations = [
    ]
