# Generated by Django 5.0.1 on 2024-01-22 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='object_id',
        ),
        migrations.AddField(
            model_name='photo',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.student'),
            preserve_default=False,
        ),
    ]
