# Generated by Django 5.0.1 on 2024-01-23 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_remove_photo_content_type_remove_photo_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.teacher'),
            preserve_default=False,
        ),
    ]
