# Generated by Django 5.0.1 on 2024-01-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_photo_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='teacher',
        ),
    ]
