# Generated by Django 5.0.1 on 2024-01-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_remove_photo_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ManyToManyField(default='No Students', related_name='classroom_relation', to='main_app.classroom'),
        ),
    ]
