# Generated by Django 5.0.1 on 2024-01-23 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_remove_photo_content_type_remove_photo_object_id_and_more'),
        ('main_app', '0033_alter_assignment_grade'),
    ]

    operations = [
    ]
