# Generated by Django 5.0.1 on 2024-01-23 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_alter_student_classroom'),
        ('main_app', '0034_merge_20240123_1934'),
    ]

    operations = [
    ]
