# Generated by Django 5.0.1 on 2024-01-23 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_merge_20240123_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='classrooms_relation', to='main_app.classroom'),
        ),
    ]
