# Generated by Django 5.0.1 on 2024-01-23 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_merge_20240123_2036'),
        ('main_app', '0036_photo_teacher_alter_teacher_classrooms'),
    ]

    operations = [
    ]
